### PR TITLE
Renderer abstraction with flexible backends (THREEJS/BLENDER)

### PR DESCRIPTION
**Pull request by taiya**
**NOTE: this is currently a draft – not ready for integration**

The purpose of this is to create a **shared** abstraction layer for visualization so that:
- it can be used in jupyter-friendly (interactive) 3D renderers (WebGL) → easy to implement via threejs
- it can be used with photorealistic (not interactive) renderers (blender) → this draft implementation
- it can be used in local (interative) 3D renderers (OpenGL) → not implemented yet

See `tensorflow_graphics/threejs/helloworld.py` for an end to end example (blender backend) that generates this image:
helloworld

The photorealistic backend will also be used to generate synthetic training datasets.
Tracking github project: https://github.com/tensorflow/graphics/projects/1

### CODE REVIEW

**Comment by ataiya** [comment]
Renamed branch to threejs and created *draft* pull request #402
(unfortunately github doesn't allow updating the branch of a pull...)

**Comment by ataiya** [comment]
@HTDerekLiu take a look, I did another pass today.
It's a bit annoying constructs like `bpy.ops.object.add(type="MESH")` do not have a return type.
Instead, I followed a pattern where I fetch it from the context as part of the Object3D superclass (via `bpy.context.object`):

```
def blender(self):
  bpy.ops.object.add(type="MESH")
  blender_object = super().blender()
  ...
  return blender_object
```

Do you have any better idea?

**Comment by HTDerekLiu** [comment]
sounds good!! having access to bpy.context.object is very useful :)

**Comment by taiya** [comment]
I'm gonna figure out keyframing next – if I recall you had something.

@HTDerekLiu can you explain this one?
```
## set gray shadow to completely white with a threshold (optional)
alphaThreshold = 0.05
shadowThreshold(alphaThreshold, interpolationMode = 'CARDINAL')
```

**Comment by HTDerekLiu** [comment]
Since it is ray tracing, it may have very very light gray color on the group far from the mesh. This is a purely image based post processing to remove those very light gray color (controlled by the threshold). It is optional, but it does make the image slightly better :)

**Comment by taiya** [comment]
Closing as sub-project moved to https://github.com/google-research/kubric

**Pull request closed without merging**
