### PR TITLE
Run PEP-8 formatting for redner

### PR DESCRIPTION
**Pull request by fulkast**
@BachiLi I noticed that the CI for your PR #138 has been failing. Hence I am attempting to fix the failure cases by basing on top of your work.

### CODE REVIEW

**Comment by BachiLi** [comment]
@googlebot I consent.

**Comment by BachiLi** [comment]
Thanks a lot! Julien complained that my PR was too big so I was in the process of breaking it down, then I went on vacation. I'll incorporate this in my following PRs.

**Comment by fulkast** [comment]
> Thanks a lot! Julien complained that my PR was too big so I was in the process of breaking it down, then I went on vacation. I'll incorporate this in my following PRs.

Great! So I managed to fix most of the styling related errors in the CI for python 3. There are still the following outstanding issues:
`
./tensorflow_graphics/models/redner/material.py:109:46: F821 undefined name 'generic_texture'
./tensorflow_graphics/models/redner/material.py:109:66: F821 undefined name 'generic_texture'
./tensorflow_graphics/models/redner/render_tensorflow.py:759:25: F821 undefined name 'd_generic_texture'
`
As they are to do with undefined variables, it would be great if you could give your input on possible solutions.

Additionally, `tensorflow_graphics/models/redner/__init__.py` triggers multiple `F403` errors for importing using the wildcard symbol i.e. `from module_name import *` which is bad because it makes it impossible to detect undefined names. As I don't know what needs to be imported from these modules, it would be great to get your input on this.

Finally, please have a look at 503fb1a where I intended to fix a pre-existing typo.

Best,
Frank

**Comment by julienvalentin** [comment]
Hi!

With the Special Interest Group, we are also trying to define the best way to 'host' work from other academics. I originally thought that creating a models folder where people would put their work is a good idea, but after discussions with TF leads it turns out its likely a false good idea. This is the reason why this is on hold for now until we come to a conclusion on this front; hopefully soon!

Thanks for your time on this ;)

Best.

**Comment by fulkast** [comment]
Hi @julienvalentin ,

Thanks for your update on this! The work here is all from @BachiLi (I based off of the open PR #138). I started this PR to help with adding fixes to the HEAD of #138 so as to pass CI.

Would the alternative be refactoring and adding the functionalities from `redner` into `graphics`?

Best,
Frank

**Comment by julienvalentin** [comment]
Hi @fulkast. There were some needed infrastructure changes, including support for submodules, linter etc.
Redner is again available but this PR is unfortunately obsolete.

**Pull request closed without merging**
